import { ActionProtocol, TelemetryRow, InventoryItem } from './types';

export const TELEMETRY_DATA: TelemetryRow[] = [
  {
    id: '1',
    tool: 'Figma Pro',
    toolShort: 'Fi',
    user: 'Sarah Jenkins',
    context: 'Marketing Dept.',
    lastUsed: '45 Days Ago',
    activity: '2 Actions / 30d',
    protocol: ActionProtocol.REMOVE,
    confidence: 0.92,
    reason: 'Sub-optimal utilization threshold.',
  },
  {
    id: '2',
    tool: 'GitHub Ent.',
    toolShort: 'Gh',
    user: 'Marcus Cole',
    context: 'Core Engineering',
    lastUsed: '2 Hrs Ago',
    activity: '450 Actions / 30d',
    protocol: ActionProtocol.KEEP,
    confidence: 0.99,
    reason: 'High density commit activity.',
  },
  {
    id: '3',
    tool: 'Slack Ent. Grid',
    toolShort: 'Sl',
    user: 'David Chen',
    context: 'External Contractor',
    lastUsed: '1 Day Ago',
    activity: '15 Actions / 30d',
    protocol: ActionProtocol.DOWNGRADE,
    confidence: 0.85,
    reason: 'Read-only profile alignment.',
  },
  {
    id: '4',
    tool: 'Notion Team',
    toolShort: 'No',
    user: 'Unknown User',
    context: 'Unassigned',
    lastUsed: 'Never',
    activity: '0 Actions / 30d',
    protocol: ActionProtocol.FLAG,
    confidence: 0.78,
    reason: 'Orphaned account detected.',
  },
];

export const INVENTORY_DATA: InventoryItem[] = [
  {
    id: '1',
    tool: 'Figma',
    category: 'Design',
    costPerSeat: 15.0,
    owner: 'Sarah J.',
    renewalDate: 'Nov 12, 2024',
    activeSeats: 42,
    ownerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQ3O6xswNFiqF5DB11tFMp6cbTAM1-y4EDqnXpXR3YFpOk_Zdh2jaSZMk2Ae_mtUMpei8X7hfYaq-HF4UYhCofp3RDpNZtWVMTcFGGV5EM3z33XJBktPsNGsqz3BNyYRVqtr7Tl4VHY6Pa2G0vv0b6KjW4J6TR5y5kVSirIUmco9rb3KVifKXibuV6vvAEDvRS4rtzm-ymgrz5bcvjUkRSwOrkau9aRTabHjDGo3y_USje_5wFt8qXek1Knl_juCggqGtoNnzCHt0_',
  },
  {
    id: '2',
    tool: 'Slack',
    category: 'Communication',
    costPerSeat: 8.75,
    owner: 'Mike R.',
    renewalDate: 'Oct 28, 2024',
    activeSeats: 156,
    flagged: true,
  },
  {
    id: '3',
    tool: 'GitHub',
    category: 'DevTools',
    costPerSeat: 21.0,
    owner: 'David K.',
    renewalDate: 'Jan 15, 2025',
    activeSeats: 89,
    ownerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAs5JHU8k82q4Xy-pT23_Gb0cx6z1WLGH80gY_xPrXiF5iODsMIB8zWdS0nGNgafS3kISnTvsZ4ARBsjq-aOeSABGXvkBUWrD_VREz5407tKXd1cZj6tqbqKxWLKN7KaM148V3fHPf9uhmmwZRWruThrJxoc1v6teCcPsLONtW4uJl9wCHrGuSaFksnZpdoFdogK4kK_oIMZNSV0rB_fkV1OzHRFyBH9GCyN978qq-JQUAr9x8pVmhAQczY-COYFt9eVYHYXzcPp-Bq',
  },
  {
    id: '4',
    tool: 'Datadog',
    category: 'Infrastructure',
    costPerSeat: 'Custom',
    owner: 'Anna L.',
    renewalDate: 'Dec 01, 2024',
    activeSeats: 12,
  },
  {
    id: '5',
    tool: 'Jira',
    category: 'Project Mgmt',
    costPerSeat: 14.5,
    owner: 'Tom B.',
    renewalDate: 'Feb 28, 2025',
    activeSeats: 156,
    ownerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDhBKcbtq_sdVFSajnkCxF_58lbCVQ2sdsJTy_ZVU8nKLg_cHqJyndOtHmvl6KVBIqOKmJiArjh-yxZm51PJl0lUgPtgdg8d17Ai4wdC3gJOTtogAclk6dtTCXcF2fGiLn4JA9cd-Ihd1UTOoyt45rROiTsDcNbGK3cGHn9CFwlRSj3jsZ9vlE_Jcydvl38cCyKEdGWF03auAKP2GMzcVh68JDrRHHZ88ujbcGmdPrj1mwhuiBSLYIyaEGhy5kw8s_f3DsImPrK-Ajk',
  },
];
